import type { Metadata } from 'next';
import './globals.css';
import { getServerSession } from 'next-auth';
import { authOption } from './api/auth/[...nextauth]/options';
import SessionSetter from '@/src/lib/SessionSeter';
import WalletProviders from '@/src/providers/WalletProviders';
import ShortcutMenu from '@/src/components/utility/ShortcutMenuModal';

export const metadata: Metadata = {
    title: 'Winterfell',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOption);

    return (
        <html lang="en">
            <body className={`antialiased bg-black`} suppressHydrationWarning>
                <WalletProviders>{children}</WalletProviders>
                <SessionSetter session={session} />
                <ShortcutMenu />
            </body>
        </html>
    );
}
