export enum COMMAND {
    WINTERFELL_BUILD = 'WINTERFELL_BUILD',
    WINTERFELL_TEST = 'WINTERFELL_TEST',
    WINTERFELL_DEPLOY_DEVNET = 'WINTERFELL_DEPLOY_DEVNET',
    WINTERFELL_DEPLOY_MAINNET = 'WINTERFELL_DEPLOY_MAINNET',
}
