export enum ClientDocsPanel {
    OVERVIEW = 'OVERVIEW',
    GETTING_STARTED = 'GETTING_STARTED',
    EDITING_AND_UNDERSTANDING = 'EDITING_AND_UNDERSTANDING',
    BUILDING_AND_TESTING = 'BUILDING_AND_TESTING',
    DEPLOYMENT = 'DEPLOYMENT',
    EXPORTING = 'EXPORTING',
    SANDBOX = 'SANDBOX',
    SANDBOX_INTRO = 'SANDBOX_INTRO',
    SANDBOX_CONFIGURATION = 'SANDBOX_CONFIGURATION',
    SANDBOX_USAGE = 'SANDBOX_USAGE',
}

export enum OverviewSubContent {
    AI_CONTRACTS = 'AI_CONTRACTS',
    SMART_EDITOR = 'SMART_EDITOR',
    ONE_CLICK_DEPLOYMENT = 'ONE_CLICK_DEPLOYMENT',
}

export enum GettingStartedSubContent {
    ROOT_WORKSPACE = 'ROOT_WORKSPACE',
    PLAYGROUND_WORKSPACE = 'PLAYGROUND_WORKSPACE',
}
