import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import SessionSetter from '@/src/lib/SessionSeter';
import { authOption } from '@/app/api/auth/[...nextauth]/options';

interface Props {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: 'Winterfell',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Props) {
    const session = await getServerSession(authOption);

    return (
        <html lang="en">
            <body
                className={`flex h-screen w-screen items-center justify-center bg-neutral-900`}
                suppressHydrationWarning
            >
                {children}
                <SessionSetter session={session} />
            </body>
        </html>
    );
}
